sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ravichandran02/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true ravichandran02/docker-react npm run test

